### PR TITLE
Update changelog.md

### PR DESCRIPTION
**Pull request by otsfan203**
Added changes.

# Title of pull request
## What I have Changed
Updates to the change log to show variable bug fix.

### CODE REVIEW

**Comment by BonfireScratch** [comment]
@otsfan203 I would be glad if you changed the ABILITIES.md and changelog.md for me, could you?

**Comment by otsfan203** [comment]
> @otsfan203 I would be glad if you changed the ABILITIES.md and changelog.md for me, could you?

Alright! I'll get working on ABILITIES.md.

**Comment by BonfireScratch** [comment]
@otsfan203 when a new feature is added, list it down

**Comment by otsfan203** [comment]
Alright! I thought you meant that changes were needed now.

**Pull request merged**
